Add `token_to_token` spec
runtimeverification/michelson-semantics pull request #250
Opened 2021-05-13 16:19 UTC by sskeirik

Note: currently this PR only includes the positive case.

Fixes: #249

2021-05-14 14:36 UTC, hjorthjort commented
Looks like this runs into `ErrorDecidePredicateUnknown` on a small non-linear expression. We should get this fixed in the backend (splitting on Z3 reporting `unknown` rather than throwing an error). In the meanwhile, we should be able to work around it by rewriting the expression(s) in question to an uninterpreted function.

2021-05-20 18:55 UTC, hjorthjort requested changes
Don't include the submodule update

2021-05-20 18:55 UTC, hjorthjort commented on Makefile
> +											DEXTER-TOKENTOTOKEN-SPEC
```suggestion
                      DEXTER-TOKENTOTOKEN-SPEC
```

2021-05-20 18:55 UTC, hjorthjort commented on tests/proofs/dexter/dexter-spec.md
> +      andBool TokenPool >Int 0
Is this strictly necessary? Should be documented if so.

2021-05-24 14:07 UTC, ehildenb commented
Can the tokens here be arbitrary contracts? If so, is that a problem for the entry-point issues? Let's double-check (and document) whether the fact that we aren't verifying entry-points is an issue for these proofs.

2021-06-01 17:37 UTC, hjorthjort approved these changes

2021-06-02 11:51 UTC, merged